services:

  bitcoind:
    build: ./bitcoind
    container_name: bitcoind-regtest
    restart: unless-stopped

    volumes:
      - bitcoind_data: /home/bitcoin/.bitcoin
      - ./scripts/init_test_wallet.sh:ro

    ports:
      - "18443:18443"   # RPC
      - "28332:28332"   # ZMQ tx
      - "28333:28333"   # ZMQ block
      - "18444:18444"   # P2P (optional LAN nodes)

    networks:
      regtest_net:
        ipv4_address: 172.28.0.2
      