
services:
  bitcoind:
    build: ./bitcoind
    container_name: bitcoind-regtest
    restart: unless-stopped
    volumes:
      - bitcoind_data:/root/.bitcoin
      - ./bitcoind/bitcoin.conf:/root/.bitcoin/bitcoin.conf:ro
      - ./scripts:/root/.bitcoin/scripts:ro
      - ./wallets:/root/.bitcoin/wallets
    ports:
      - "18443:18443"
      - "28332:28332"
      - "28333:28333"
      - "18444:18444"
    entrypoint: ["/root/entrypoint.sh"]

volumes:
  bitcoind_data: