version: '3.8'

services:
  bitcoind:
    build: ./bitcoind
    container_name: bitcoind-regtest
    restart: unless-stopped
    volumes:
      - bitcoind_data:/root/.bitcoin
      - .bitcoin.conf:/root/.bitcoin/bitcoin.conf:ro
    ports:
      - "18443:18443"
      - "28332:28332"
      - "28333:28333"
      - "18444:18444"
    entrypoint: ["/root/entrypoint.sh"]
    networks: 
      regtest_net:
        ipv4_address: 172.28.0.2

  # Hilfs-Container für wallet initialisirung
  bitcoind-init:
    build: ./bitcoind
    container_name: bitcoind-regtest-wallets
    volumes:
      - bitcoind_data:/home/bitcoin/.bitcoin
      - ./scripts/init_test_wallet.sh:/scripts/init_test_wallet.sh:ro
    networks:
      regtest_net:
    depends_on:
      - bitcoind
    # Warteschleife
    entrypoint: >
      /bin/bash -c "
      echo '[init] Waiting for RPC server...';
      until bitcoin-cli -regtest -rpcuser=user -rpcpassword=pass -rpcconnect=172.28.0.2 getblockchaininfo >/dev/null 2>&1; do
        sleep 1;
      done;
      echo '[init] Node is ready. Running wallet initialization...';
      bash /scripts/init_test_wallet.sh;
      echo '[init] Wallet initialization completed.';
      "

volumes:
  bitcoind_data:

networks:
  regtest_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16