
# REGTEST CORE
regtest=1
server=1
listen=1

txindex=1
fallbackfee=0.0002

printtoconsole=1


rpcuser=user
rpcpassword=pass

rpcbind=10.50.0.10
rpcallowip=10.50.0.0/24
rpcport=18443


# ZMQ EVENT STREAM
zmqpubrawtx=tcp://10.50.0.10:28332
zmqpubrawblock=tcp://10.50.0.10:28333


# WALLET
disablewallet=0
walletdir=/home/bitcoin/.bitcoin/wallets
